### ISSUE TITLE
Typo in pipeline.json included with Raidionics-MRI_GBM_multiclass-ONNX-v12.zip 

### ISSUE THREAD

**Issue by ft-zhang** [raidionics/Raidionics-models#1]
Hi @dbouget,

In step 5 of pipeline.json included with Raidionics-MRI_GBM_multiclass-ONNX-v12.zip, the description suggests registration from T1w (T0) to T1CE (T0) but the current version of the json includes two instances of "T1-w" for both moving and fixed sequences. Changing the fixed to "T1-CE" allows the pipeline to run smoothly. Hope this is fixed with the next release!

**Comment by dbouget** [comment]
Hi @ft-zhang,

Thanks for pointing it out! I've updated the json files for the three "multiclass" models in the current release.
